### PR TITLE
Fixed bugs and add progress

### PR DESCRIPTION
**Pull request by TheBossMagnus**
- Fixed a bug involving character parsing (in the header)
- Fixed script interrupting when the request fails to convert a link
- Added a message showing the URLs conversion status (x out of the total)
- Minor lintings

Ty, really helpful script

### CODE REVIEW

**Comment by hitsomeshots** [comment]
Approved with some changes!

**Comment by TheBossMagnus** [comment]
Would you be interested in making this async with aiohhttp? It would improve perf in a major way (especially with many links), but it will need to depend on aiohttp instead of request.

**Comment by hitsomeshots** [comment]
Ill for sure that when i have some time

**Comment by TheBossMagnus** [comment]
I can PR it if you like, I've a decent experience in iohttp

**Comment by hitsomeshots** [comment]
pushed the async update let me know if it has any bugs

**Comment by TheBossMagnus** [comment]
Looks ok, I'll give it a deeper look soon

**Comment by hitsomeshots** [comment]
they added  a captcha to the site any way i could find the anchor link because it changes for every download link if u can help me with that i can push out an update.

**Comment by ghost** [comment]
> they added a captcha to the site any way i could find the anchor link because it changes for every download link if u can help me with that i can push out an update.

forgot to mention, aiodns has issue with windows :/

**Pull request merged**
